In [6]:
import sys, os
sys.path.append(os.pardir)
from common.util import im2col
import numpy as np

In [3]:
class Convolution():
    def __init__(self, W, b, stride=1, pad=0):
        self.W = W
        self.b = b
        self.stride = stride
        self.pad = pad
    
    def forward(self, x):
        FN, C, FH, FW = self.W.shape
        N, C, H, W = x.shape
        out_h = int(1 + (H + 2*self.pad - FH) / self.stride)
        out_w = int(1 + (W + 2*self.pad - FW) / self.stride)
        
        col = im2col(x, FH, FW, self.stride, self.pad)
        col_W = self.W.reshape(FN, -1)
        out = np.dot(col, col_W)
        
        out = out.reshape(N, out_h, out_W, -1).transpose(0, 3, 1, 2)
        
        return out

In [4]:
class Pooling():
    def __init__(self, pool_h, pool_w, stride=1, pad=0):
        self.pool_h = pool_h
        self.pool_w = pool_w
        self.stride = stride
        self.pad = pad
    
    def forward(self, x):
        N, C, H, W = x.shape
        out_h = int(1 + (H - self.pool_h) / self.stride)
        out_w = int(1 + (W - self.pool_w) / self.stride)
        
        col = im2col(x, self.pool_h, self.pool_w, self.stride, self.pad)
        col = col.reshape(-1, self.pool_h*self.pool_w)
        
        out = np.max(col, axis=1)
        
        out = out.reshape(N, out_h, out_w, C).transpose(0, 3, 1, 2)
        
        return out

In [125]:
# col = im2col(x, self.pool_h, self.pool_w, self.stride, self.pad)
sample = np.arange(3*4*4)

In [126]:
sample = sample.reshape(1, 3, 4, 4)

In [127]:
sample

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]])

In [128]:
col = im2col(sample, 2, 2, stride=2)
col

array([[ 0.,  1.,  4.,  5., 16., 17., 20., 21., 32., 33., 36., 37.],
       [ 2.,  3.,  6.,  7., 18., 19., 22., 23., 34., 35., 38., 39.],
       [ 8.,  9., 12., 13., 24., 25., 28., 29., 40., 41., 44., 45.],
       [10., 11., 14., 15., 26., 27., 30., 31., 42., 43., 46., 47.]])

In [129]:
col = col.reshape(-1, 4)

In [130]:
col

array([[ 0.,  1.,  4.,  5.],
       [16., 17., 20., 21.],
       [32., 33., 36., 37.],
       [ 2.,  3.,  6.,  7.],
       [18., 19., 22., 23.],
       [34., 35., 38., 39.],
       [ 8.,  9., 12., 13.],
       [24., 25., 28., 29.],
       [40., 41., 44., 45.],
       [10., 11., 14., 15.],
       [26., 27., 30., 31.],
       [42., 43., 46., 47.]])

In [131]:
out = np.max(col, axis=1)

In [132]:
out
# out.shape

array([ 5., 21., 37.,  7., 23., 39., 13., 29., 45., 15., 31., 47.])

In [133]:
out = out.reshape(1, 2, 2, 3)
out

array([[[[ 5., 21., 37.],
         [ 7., 23., 39.]],

        [[13., 29., 45.],
         [15., 31., 47.]]]])

In [134]:
out = out.reshape(1, 2, 2, 3).transpose(0, 3, 1, 2)
out

array([[[[ 5.,  7.],
         [13., 15.]],

        [[21., 23.],
         [29., 31.]],

        [[37., 39.],
         [45., 47.]]]])